# Development version
version: '2'
services:
  cma-web:
    build:
     context: src/main/docker/wildfly
     dockerfile: Dockerfile-dev
    ports:
     - "8080:8080"
     - "9990:9990"
     - "9999:9999"
     - "8787:8787"
  cma-db:
    ports:
     - "5432:5432"
